apiVersion: apps/v1
kind: Deployment
metadata:
  name: daksh-asl-desktop # Change this to your initials
  namespace: autoslug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daksh-asl-desktop # Change this to your initials
  template:
    metadata:
      labels:
        app: daksh-asl-desktop # Change this to your initials
    spec:
      hostname: daksh-asl-desktop # Change this to your initials
      securityContext: # Pod-level security context (optional)
        runAsUser: 1000 # UID for the user
        runAsGroup: 1000 # GID for the group
        fsGroup: 1000 # Ensure mounted volumes have the correct group permissions
      containers:
      - name: daksh-asl-desktop # Change this to your initials
        image: ghcr.io/selkies-project/nvidia-glx-desktop:22.04-20240815104538 # If you face compatibility issues, replace "latest" with "22.04-20240815104538" or any other tag found here https://github.com/selkies-project/docker-nvidia-glx-desktop/pkgs/container/nvidia-glx-desktop
        env:
        - name: TZ
          value: "UTC"
        - name: DISPLAY_SIZEW
          value: "1920"
        - name: DISPLAY_SIZEH
          value: "1080"
        - name: DISPLAY_REFRESH
          value: "60"
        - name: DISPLAY_DPI
          value: "96"
        - name: DISPLAY_CDEPTH
          value: "24"
        - name: VIDEO_PORT
          value: "DFP"
        - name: PASSWD
          valueFrom:
            secretKeyRef:
              name: my-pass
              key: my-pass  
        - name: SELKIES_ENCODER
          value: "nvh264enc"
        - name: SELKIES_ENABLE_RESIZE
          value: "false"
        - name: SELKIES_VIDEO_BITRATE
          value: "8000"
        - name: SELKIES_AUDIO_BITRATE
          value: "128000"
        - name: SELKIES_FRAMERATE
          value: "60"
        - name: SELKIES_ENABLE_BASIC_AUTH
          value: "true"
        - name: SELKIES_TURN_REST_URI
          value: "http://turn-rest.nrp-nautilus.io"
        - name: SELKIES_TURN_PROTOCOL
          value: "udp"
        - name: SELKIES_TURN_TLS
          value: "false"
        stdin: true
        tty: true
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: 48Gi
            cpu: "6"
            nvidia.com/gpu: "1"
            ephemeral-storage: 70Gi
          requests:
            memory: 48Gi
            cpu: "6"
            nvidia.com/gpu: "1"
            ephemeral-storage: 70Gi
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /cache
          name: cache-vol
        - mountPath: /home/ubuntu/persistent
          name: root-vol
        # - mountPath: /home/ubuntu/asl/data
        #   name: asl-data
        # - mountPath: /home/ubuntu/asl/persistent
        #   name: asl-perst
      dnsPolicy: None
      dnsConfig:
        nameservers:
        - 8.8.8.8
        - 8.8.4.4
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      - name: cache-vol
        persistentVolumeClaim:
          claimName: desktop-cache # Change this to your initials
      - name: root-vol
        persistentVolumeClaim:
          claimName: aria-persistent # Change this to your initials
      # - name: asl-data
      #   persistentVolumeClaim:
      #     claimName: asl-dataset
      # - name: asl-perst
      #   persistentVolumeClaim:
      #     claimName: asl-persistent
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: NotIn
                values:
                - ucsd-suncave
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-GeForce-RTX-3090
                - NVIDIA-A10
                - NVIDIA-GeForce-RTX-4090
                - NVIDIA-TITAN-RTX
                - NVIDIA-RTX-A5000
                - NVIDIA-A40
                - NVIDIA-L40
                - NVIDIA-RTX-A6000
                - Quadro-RTX-8000
                - NVIDIA-A100-SXM4-80GB
                - Tesla-V100-SXM2-32GB