apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aria-persistent
  namespace: autoslug
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi